services:
  # redis:
  #   image: 'bitnami/redis:latest'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - 6379:6379

  actg-contacts:
    image: shau1943/actg-contacts:latest
    pull_policy: always
    container_name: actg-contacts
    restart: unless-stopped
    command: 
      - bash 
      - -c 
      - |
        mount -a && python -m src.main
    privileged: true
    volumes:
      - ./config.json:/actg-contacts/config.json