services:
  actg-contacts:
    build:
      context: .
    image: shau1943/actg-contacts:latest
    container_name: actg-contacts
    restart: unless-stopped
    volumes:
        - ./config.json:/actg-contacts/config.json