services:
  actg-contacts:
    image: shau1943/actg-contacts:main
    container_name: actg-contacts
    restart: unless-stopped
    privileged: true
    volumes:
      - ./config.json:/actg-contacts/config.json